### ISSUE TITLE
Add control to common PHP settings like memory_limit, upload_max_filesize, max_execution_time

### ISSUE THREAD

**Issue by MurzNN** [bkuhl/fpm-nginx#39]
Will be good to have ability to tune the common PHP parameters like:
- memory_limit
- upload_max_filesize
- max_execution_time

Is it possible now? If not, how hard to implement this?

**Comment by bkuhl** [comment]
You can tweak these settings via your own Dockerfile when building your application's container.  There's a few approaches... I'd recommend adding a new `php.ini` with your customized parameters and naming it in a way that it loads last.

**Comment by bkuhl** [comment]
To elaborate a little more... in this case, you can add a php.ini file to `/usr/local/etc/php/conf.d/`.  In this directory, php loads the ini files in alphabetical order, so you might want to name it something like `z-production.ini`.  As PHP reads other ini files, your settings would override any from other files since they're loaded last.

**Comment by MurzNN** [comment]
I know that I can customize all of this via custom `php.ini`, but tuning those settings is a very common task! So will be good to expose them as ENV variables like here https://hub.docker.com/r/nodeartio/php to simplify managing.

**Comment by bkuhl** [comment]
A PR would be welcome!
